"""login required flag

Revision ID: 9bc82e2acab3
Revises: d23445bc6f67
Create Date: 2021-06-09 23:06:58.825509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc82e2acab3'
down_revision = 'd23445bc6f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('login_required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'login_required')
    # ### end Alembic commands ###
