"""forgot-password model added

Revision ID: a43de0e83f23
Revises: 35f37cf69fc2
Create Date: 2021-06-17 16:36:32.707332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a43de0e83f23"
down_revision = "35f37cf69fc2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forgot_password",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("token", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("forgot_password")
    # ### end Alembic commands ###
